### ISSUE TITLE
React Native 0.70.0

### ISSUE THREAD

**Issue by danyzor** [Malaa-tech/react-native-simple-line-chart#2]
Hello,

I am looking forward to trying your library out, but I am using react-native 0.68.

Is there a particular reason for putting react-native >= 0.70.0 in your peerDependencies list?

Thanks a lot!

**Comment by WadhahEssam** [comment]
hello @danyzor  sorry for late response I have to enable notifications for the project. 

to be honest its not necessary for the app to be >= 70, did you face any issues using it?

**Comment by danyzor** [comment]
I can confirm it works on react native 0.68. Thanks for your response and your library! :)
