### ISSUE TITLE
Chart not showing up on Android

### ISSUE THREAD

**Issue by aljadan** [Malaa-tech/react-native-simple-line-chart#3]
I've noticed a weird issue on Android where the chart isn't visible the first time it's supposed to render. However, when the chart data gets updated, it shows up and seems to work just fine
Looks like it might only be a problem on the first render and only on Android.

For more details, here's a [Simple Example](https://github.com/aljadan/react-native-simple-line-chart) of what I'm talking about.

https://github.com/Malaa-tech/react-native-simple-line-chart/assets/111672775/9eff547f-c7d5-4fb7-939f-cc98a842943d

https://github.com/Malaa-tech/react-native-simple-line-chart/assets/111672775/91c55b67-8c8f-4ab2-b2f0-88d64b9fbd1d

**Comment by aljadan** [comment]
Just a heads up, this issue kinda shows up randomly, about once in every 20 times

**Comment by WadhahEssam** [comment]
Hey @aljadan thanks for the support, yeah we thought we fixed that but it appears that its not fixed yet, I have a theory that I will test, and we will update the library soon

**Comment by WadhahEssam** [comment]
this should be fixed now with 0.33 release @aljadan 🙏 thanks with helping with reproducing it I added the reset button to the example
